.Dd September 15, 2018
.Dt LSW 1
.Os mmutils
.Sh NAME
.Nm lsm
.Nd list active/connected xrandr monitors
.Sh SYNOPSIS
.Nm lsm
.Op Fl a
.Op Fl h
.Sh DESCRIPTION
.Nm
gets a list of monitors (active, connected, and primary).
.Pp
By default,
.Nm
lists all active monitors.
.Bl -tag -width Ds
.It Fl a
List all active monitors as well as all connected monitors
(monitors that are physically connected to a graphics card, but don't have an
active X desktop assigned).
.It Fl p
Get the primary monitor.
.It Fl h
Output a usage message.
.El
.sp
.Sh SEE ALSO
.sp
\fBpfm\fR(1),
\fBmattr\fR(1)
