.Dd September 15, 2018
.Dt MATTR 1
.Os mmutils
.Sh NAME
.Nm mattr
.Nd get information about a monitor
.Sh SYNOPSIS
.Nm mattr
.Op Fl h
.Op Fl c
.Op Cm inwhxys
.Ar wid|mid
.Sh DESCRIPTION
.Nm
gets information (connection status, active status, width, height, x/y offset)
about a monitor. A monitor can be specified by its xrandr id (\fImid\fR), by a
window id (\fIwid\fR). The information is printed to standard output. What
information is presented depends on the commands given to.
.sp
The queried arguments are printed in the order they are requested,
separated by a space. If no commands are given,
.Nm
will return 0 if the monitor exist, and 1 otherwise.
.Bl -tag -width Ds
.It Cm n
Print
.Ar mid Ns .
.It Cm i
Print
.Ar mid Ns \ (wmutils compat).
.It Cm w
Print
.Ar mid Ns \(cqs width.
.It Cm h
Print
.Ar mid Ns \(cqs
height.
.It Cm x
Print
.Ar mid Ns \(cqs
.EQ
x
.EN
offset.
.It Cm y
Print
.Ar mid Ns \(cqs
.EQ
y
.EN
offset.
.It Cm s
Print the
.Ar mid/wid
.EN
passed as an argument. Useful only when 
.Ar wid
is passed. Otherwise equivalent to 
.Ar n Ns .
.sp
.Sh SEE ALSO
.sp
\fBlsm\fR(1),
\fBpfm\fR(1)

