.Dd September 15, 2018
.Dt MMUTILS 1
.Os mmutils
.Sh NAME
.Nm mmutils
.Nd xrandr monitor information querying utilities
.Sh DESCRIPTION
.Nm
is a set of utilities to easily get xrandr monitor information.
.Sh COMMANDS
.PP
\fBlsm\fR(1)
    Get a list of monitors.
.sp
\fBpfm\fR(1)
    Get xrandr if of the focused monitor.
.sp
\fBmattr\fR(1)
    Get information about a monitor.
.sp
.Sh SEE ALSO
.sp
\fBlsm\fR(1),
\fBpfm\fR(1),
\fBmattr\fR(1)

