.Dd September 15, 2018
.Dt MMUTILS 1
.Os mmutils
.Sh NAME
.Nm mmutils
.Nd window manipulation utilities
.Sh DESCRIPTION
.Nm
is a set of utilities to easily get xrandr monitor information
.Sh COMMANDS
.Bl -tag -width Ds -offset 60
.It lsm
get a list of monitors
.It pfm
get xrandr if of the focused monitor
.It mattr
get information about a monitor
.El
.Sh SEE ALSO
.Xr lsm 1 ,
.Xr pfm 1 ,
.Xr mattr 1 
