.Dd September 15, 2018
.Dt PFM 1
.Os mmutils
.Sh NAME
.Nm pfm
.Nd print focused monitor
.Sh SYNOPSIS
.Nm pfm
.Sh DESCRIPTION
Gets the xrandr id of the focused monitor.
The focused monitor is determined by the pointer coordinates. Whichever
monitor holds the pointer is considered as "focused".
.Sh SEE ALSO
.Xr lsm 1
.Xr mattr 1
